# Generated by Django 3.2 on 2021-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
