# Generated by Django 3.2 on 2021-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210624_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
