# Generated by Django 3.2 on 2021-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bill_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
