# Generated by Django 3.2 on 2021-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210625_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.BooleanField(default=False),
        ),
    ]
