# Generated by Django 3.2 on 2021-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
