# Generated by Django 3.2 on 2021-06-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_bill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='url',
        ),
    ]
