# Generated by Django 3.2 on 2021-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_bill_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='avgCurrent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='voltage',
            field=models.FloatField(null=True),
        ),
    ]
